### ISSUE TITLE
Missing solution for assigment 3

### ISSUE THREAD

**Issue by thorsten-papenbrock** [mdrkb/akka-exercise#1]
Dear authors,

there is no solution for assignment 3 in this repository. Did you forget to push that solution or did you give up the course. Without a solution for both assignments, you are not permitted to the final exam. Please contact me as soon as possible to resolve the issue!

Best,
Thorsten

**Comment by mdrkb** [comment]
Hello,

We pushed the code to another repo by mistake. I have added the missing codes. And, sorry for the late reply.

Regards,
Rakibul

**Comment by thorsten-papenbrock** [comment]
Hi Rakibul,

ok that was kind of what I expected. I will update the repo and test your solution.

Best,
Thorsten
